### ISSUE TITLE
Additional elements mess up element names

### ISSUE THREAD

**Issue by DavidJCobb** [matortheeternal/ztools#23]
The container for responses is mislabeled as "Conditions," while the container for conditions is labeled "Unknown." The previous-sibling of the responses container (and next-sibling of DNAM) is labeled "Responses."

zEdit 0.1.1. Skyrim Classic. If this doesn't happen to every INFO, then suitable test-cases include the two INFOs in Cobb Positioner's v2.1.0 release.

**Comment by matortheeternal** [comment]
Should have been fixed in development a few days ago when I fixed the issue with additional elements and `GetDefNames` in XEditLib.

**Comment by matortheeternal** [comment]
Resolved.
